---
name: GitHub Pages

on:
  push:
    # branches: ["dev", "dev-update"]
    branches: ["NEVER" ,'dev-test-pages']
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions: write-all

jobs:
  # Pages:
  #   uses: dennykorsukewitz/DK4/.github/workflows/reusable.pages.yml@dev

  Trigger-GitHub-Pages:
    name: Trigger GitHub Pages
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: |
          gh workflow run --repo dennykorsukewitz/dennykorsukewitz.github.io pages.yml --ref dev
        env:
          # GITHUB_TOKEN: ${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
