---
name: GitHub Pages

on:
  push:
    # branches: ["dev", "dev-update"]
    branches: ["NEVER"]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions: write-all

jobs:
  Pages:
    uses: dennykorsukewitz/DK4/.github/workflows/reusable.pages.yml@dev
